const auto_start = document.getElementById("automatic_start")
const man_start = document.getElementById("man_start")
const main_wrapper = document.getElementById("main_wrapper")
const swipe_left = document.getElementById("left")
const swipe_right = document.getElementById("right")
const main = document.getElementsByClassName("main")
console.log(man_start)
console.log(auto_start)
console.log(man_start.offsetHeight)
const offsetHeight = man_start.offsetHeight
const offsetHeight_str = offsetHeight.toString()
console.log(offsetHeight_str)
